import React from 'react';
import {Pressable,StyleSheet,Text,View} from 'react-native';
import {t,ui} from '../../theme';
const sp=ui.spacing;
export function Action({children,onPress,quiet=false,disabled=false,accessibilityLabel}){return <Pressable accessibilityRole="button" accessibilityLabel={accessibilityLabel} disabled={disabled} onPress={onPress} style={({pressed})=>[s.action,quiet&&s.quiet,pressed&&s.pressed,disabled&&s.disabled]}><Text style={[s.actionText,quiet&&s.quietText]}>{children}</Text></Pressable>}
export function Intro(){return <View style={s.intro}><Text accessibilityRole="header" style={s.title}>Make sense of your policy.</Text><Text style={s.body}>Fictional policy wording · 6 everyday questions · source passages only</Text></View>}
export function TopicList({data,onOpen,active,opener}){return <View style={s.list}>{data.sections.map((section,index)=><Pressable key={section.id} ref={el=>{if(opener)opener.current[index]=el}} accessibilityRole="button" accessibilityState={{selected:active===index}} onPress={()=>onOpen(index)} style={({pressed})=>[s.topic,active===index&&s.topicActive,pressed&&s.pressed]}><View style={s.grow}><Text style={s.label}>{section.title}</Text><Text style={s.small}>{section.excerpts.length?`${section.excerpts.length} matching passage${section.excerpts.length===1?'':'s'}`:'Not found in this reading'}</Text></View><Text style={s.symbol}>›</Text></Pressable>)}</View>}
export function Passage({section}){return <View style={s.passage}><Text style={s.label}>{section.title}</Text><Text style={s.small}>{section.help}</Text>{section.excerpts.length?section.excerpts.map((excerpt,index)=><View key={`${excerpt.location}-${index}`} style={s.excerpt}><Text style={s.location}>{excerpt.location}</Text><Text selectable style={s.body}>{excerpt.text}</Text></View>):<Text style={s.body}>No matching passage was found in this reading. This does not mean the benefit is excluded. Check the full wording and ask the insurer.</Text>}</View>}
export const s=StyleSheet.create({variant:{gap:sp.lg,maxWidth:ui.layout.reading,width:'100%'},intro:{gap:sp.xs},title:{fontSize:ui.type.title,lineHeight:ui.leading.title,fontWeight:ui.weight.strong,color:t.ink},body:{fontSize:ui.type.body,lineHeight:ui.leading.body,color:t.ink},small:{fontSize:ui.type.small,lineHeight:ui.leading.small,color:t.muted},label:{fontSize:ui.type.body,lineHeight:ui.leading.body,fontWeight:ui.weight.strong,color:t.ink},list:{gap:sp.xs},topic:{minHeight:ui.controls.height,flexDirection:'row',alignItems:'center',gap:sp.md,padding:sp.sm,borderRadius:ui.radius.small,backgroundColor:t.paper},topicActive:{backgroundColor:t.wash},grow:{flex:1,minWidth:0},symbol:{fontSize:ui.type.section,color:t.green},passage:{gap:sp.sm,padding:sp.md,backgroundColor:t.wash,borderRadius:ui.radius.small},excerpt:{gap:sp.xs},location:{fontSize:ui.type.small,lineHeight:ui.leading.small,fontWeight:ui.weight.strong,color:t.muted},action:{minHeight:ui.controls.height,paddingHorizontal:sp.md,paddingVertical:sp.sm,justifyContent:'center',alignSelf:'flex-start',borderRadius:ui.radius.medium,backgroundColor:t.green},quiet:{backgroundColor:t.paper},actionText:{fontSize:ui.type.body,lineHeight:ui.leading.body,fontWeight:ui.weight.strong,color:t.paper},quietText:{color:t.green},pressed:{opacity:.8},disabled:{opacity:ui.controls.disabledOpacity}});
