const assert=require('node:assert/strict');
const {evaluateOffer,compareOffers,evaluateSurplus,evaluateTermLife,xirr}=require('./mvpMath');
const near=(a,b,t=.02)=>assert.ok(Math.abs(a-b)<t,`${a} != ${b}`);
const base={amount:120000,annualRate:12,months:12,loanType:'Personal',asOfDate:'2026-01-01'};
near(evaluateOffer(base).interest,7942.2556968);
const flat=evaluateOffer({...base,rateType:'flat',processingFee:1000,insurance:500});near(flat.total,136080);near(flat.netDisbursal,118320);assert.ok(flat.effectiveAPR>24);assert.ok(flat.equivalentReducingRate>21);
const pct=evaluateOffer({...base,processingFee:1,processingFeeType:'percent'});near(pct.fees,1416);near(pct.netDisbursal,118584);
const financed=evaluateOffer({...base,insurance:10000,insuranceMode:'financed'});near(financed.financedPrincipal,130000);near(financed.netDisbursal,120000);assert.ok(financed.interest>evaluateOffer(base).interest);
assert.equal(evaluateOffer({...base,loanType:'Home',rateType:'flat'}).rateType,'reducing');
assert.equal(compareOffers([base,{...base,annualRate:10}]).winnerIndex,1);
assert.equal(compareOffers([base,{...base,amount:100000}]).rankingBasis,'apr');
assert.equal(compareOffers([base,{...base,months:24}]).rankingBasis,'apr');
assert.equal(compareOffers([base,{...base,loanType:'Home'}]).winnerIndex,null);
assert.throws(()=>compareOffers([base,base,base,base]));
near(xirr(1000,[1100],'2024-01-31'),(Math.pow(1.1,365/29)-1)*100,.0001);
const loan={balance:120000,annualRate:12,months:12,surplus:20000,investmentRate:0,reserve:0,asOfDate:'2026-01-01'};
const result=evaluateSurplus(loan);near(result.shorter.saving,2408.0860826);near(result.investment.prepayFutureValue,22408.0860826);assert.equal(result.recommendation,'prepay');
const all=evaluateSurplus({...loan,surplus:130000,prepaymentFee:1000});near(all.prepayment,120000);near(all.investment.prepayFutureValue,9000+all.emi*12);near(all.shorter.total,121000);assert.equal(all.route,'foreclosure');
const short=evaluateSurplus({...loan,surplus:120000,prepaymentFee:1000});near(short.prepayment,0);near(short.foreclosureShortfall,1000);assert.equal(short.recommendation,'reserve');
const percent=evaluateSurplus({...loan,prepaymentFee:2,prepaymentFeeType:'percent'});near(percent.prepayment+percent.fees,20000);
assert.equal(evaluateSurplus({...loan,reserve:20000}).recommendation,'reserve');
assert.equal(evaluateSurplus({...loan,reserve:undefined}).recommendation,'review');
assert.equal(evaluateSurplus({...loan,reserve:undefined,monthlyExpenses:10000}).recommendation,'reserve');
const zero=evaluateSurplus({...loan,annualRate:0});near(zero.investment.advantage,0);assert.equal(zero.recommendation,'tie');
const parity=evaluateSurplus({...loan,investmentRate:100*(Math.pow(1.01,12)-1)});near(parity.investment.advantage,0);assert.equal(parity.recommendation,'tie');
assert.equal(evaluateSurplus({...loan,currentEMI:5000}).recommendation,'review');
assert.ok(evaluateSurplus({...loan,rateType:'flat'}).emi>result.emi);
const taxed=evaluateSurplus({...loan,investmentRate:10,taxSlab:30,loanTaxBenefitEligible:true,annualLoanTaxBenefit:2000});near(taxed.postTaxInvestmentRate,7);assert.ok(taxed.postTaxLoanRate<result.postTaxLoanRate);
near(evaluateSurplus({...loan,annualLoanTaxBenefit:2000}).postTaxLoanRate,result.postTaxLoanRate);
for(const bad of [{months:0},{months:1.5},{balance:-1},{surplus:-1},{investmentRate:-100},{reserve:-1}])assert.throws(()=>evaluateSurplus({...loan,...bad}));
assert.throws(()=>evaluateOffer({...base,processingFee:120000}));
const policy=evaluateTermLife({cover:10000000,premium:1000,premiumFrequency:'monthly',age:30,policyTerm:30,annualIncome:1200000,liabilities:1000000});near(policy.annualPremium,12000);near(policy.gap,3000000);assert.equal(policy.renewalDue,null);
console.log('MVP financial contracts passed: dated XIRR, GST, financed premiums, mixed-basis ranking, affordability, liquidity, flat conversion, net cashflow parity, tax assumptions and term-life heuristic.');

assert.equal(evaluateOffer({...base,loanType:'Home loan',rateType:'flat'}).rateType,'reducing');
const costly=evaluateSurplus({...loan,prepaymentFee:15000,investmentRate:7});assert.ok(costly.investment.advantage>0);assert.equal(costly.recommendation,'invest');
near(evaluateSurplus({...loan,investmentRate:-10,taxSlab:30}).postTaxInvestmentRate,-10);
for(const bad of [{age:30.5},{dependents:1.5},{policyTerm:100}])assert.throws(()=>evaluateTermLife({cover:100000,premium:1000,age:30,policyTerm:30,...bad}));
