const assert = require('node:assert/strict');
const { reviewPolicy, redact } = require('./policyReview.cjs');
const review = reviewPolicy('# Insurance exclusions\n\nHospital treatment is not covered unless approved.\nSecond condition: prior authorisation is required.\n\nPremium: Rs 12,000');
assert.match(review.sections[0].excerpts[0].text, /not covered unless approved/);
assert.match(review.sections[0].excerpts[0].text, /prior authorisation/);
assert.match(review.sections[1].excerpts[0].text, /^Insurance exclusions/);
assert.equal(review.sections[2].status, 'not found in extracted text');
assert.equal(review.sections[0].status, 'matching passages');
assert.equal(review.sections[0].excerpts[0].location, 'Extracted paragraph 2');
const injection = '<script>alert("insurance cover")</script>';
assert.equal(reviewPolicy(injection).sections[0].excerpts[0].text, injection);
const filtered = redact('Insured name: Person Example\nAddress: Example Road\nPolicy number: ABC123\nContact: person@example.com +91 9876543210\nABCDE1234F 1234 5678 9012\nPremium: Rs 12,000\nCover: Rs 500000');
for (const value of ['Person Example', 'Example Road', 'ABC123', 'person@example.com', '9876543210', 'ABCDE1234F', '1234 5678 9012']) assert.ok(!filtered.includes(value));
assert.match(filtered, /Rs 12,000/);
assert.match(filtered, /Rs 500000/);
assert.ok(reviewPolicy('cover '.repeat(170000)).truncated);
assert.equal(reviewPolicy('cover '.repeat(170000)).sections[0].excerpts.length, 0);
const longReview = reviewPolicy('Insurance policy\n\n' + 'Document wording. '.repeat(40000) + '\n\nWaiting period: 30 days.');
assert.equal(longReview.truncated, false);
assert.match(longReview.sections[2].excerpts[0].text, /Waiting period: 30 days/);
const many = reviewPolicy(Array.from({ length: 10 }, (_, i) => `Insurance coverage clause ${i}`).join('\n\n'));
assert.equal(many.sections[0].excerpts.length, 6);
assert.equal(many.sections[0].omitted, 4);
assert.ok(reviewPolicy('My cover letter includes benefits and fees.').sections.every(section => section.excerpts.length === 0));
assert.ok(reviewPolicy('').sections.every(section => section.excerpts.length === 0));
const bold = reviewPolicy('Insurance policy\n\n**Exclusions**\n\nRoutine OPD is not covered.');
assert.equal(bold.sections[1].excerpts.length, 1);
assert.equal(bold.sections[1].excerpts[0].text, 'Exclusions\nRoutine OPD is not covered.');
assert.equal(bold.sections[1].excerpts[0].location, 'Extracted paragraph 3');
assert.equal(reviewPolicy('Insurance policy\n\n**Exclusions**').sections[1].excerpts.length, 0);
assert.equal(reviewPolicy('Insurance policy\n\n# Exclusions').sections[1].excerpts.length, 0);
console.log('Policy evidence tests passed.');
